defaults:
  boot_order:
  - network
  - disk
  cpus: 2
  disk_size: 20
  memory: 2048
  network: br0
vms:
  testvm1:
    cpus: 2
    disk: images/vms/testvm1.qcow2
    mac: 52:54:00:93:ff:5a
    memory: 2048
    name: testvm1
    network: br0
    serial_port: 5001
    state: running
    vnc_port: 1
